package com.bookdecision.application.userdataset;

import com.bookdecision.application.InputLimits;
import com.bookdecision.application.Isbn13Validator;
import com.bookdecision.domain.OfferStatus;
import com.bookdecision.domain.PlatformOffer;
import com.bookdecision.domain.RepeatPolicy;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVParser;
import org.apache.commons.csv.CSVRecord;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.nio.ByteBuffer;
import java.nio.charset.CharacterCodingException;
import java.nio.charset.CodingErrorAction;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

@Component
public final class UserDatasetCsvParser {

    /** The user-facing format generated by the template and example download endpoints. */
    public static final String SCHEMA_VERSION = "用户报价-v2";
    /** Kept so files downloaded before the v2 rollout remain usable. */
    public static final String LEGACY_SCHEMA_VERSION = "user-offer-v1";
    public static final List<String> HEADERS = List.of(
            "数据格式版本",
            "ISBN",
            "书名",
            "数量",
            "平台",
            "回收状态",
            "单本价格（元）",
            "重复书限制"
    );
    public static final List<String> LEGACY_HEADERS = List.of(
            "schema_version",
            "isbn",
            "title",
            "quantity",
            "platform_id",
            "status",
            "unit_price_yuan",
            "repeat_policy"
    );
    private static final Map<String, String> USER_PLATFORM_IDS = Map.of(
            "平台A", "platform-a",
            "平台B", "platform-b",
            "平台C", "platform-c",
            "平台D", "platform-d",
            "平台E", "platform-e"
    );
    private static final Map<String, OfferStatus> USER_STATUSES = Map.of(
            "回收", OfferStatus.ACCEPTED,
            "不回收", OfferStatus.REJECTED,
            "未知", OfferStatus.UNKNOWN
    );
    private static final Map<String, RepeatPolicy> USER_REPEAT_POLICIES = Map.of(
            "", RepeatPolicy.INHERIT_PLATFORM,
            "0", RepeatPolicy.ONE_PER_ORDER,
            "1", RepeatPolicy.UP_TO_INVENTORY,
            "遵循平台默认", RepeatPolicy.INHERIT_PLATFORM,
            "每单同书限一本", RepeatPolicy.ONE_PER_ORDER,
            "可按填写数量回收", RepeatPolicy.UP_TO_INVENTORY
    );
    private static final long MAX_PRICE_CENTS = 1_000_000L;

    public ParsedUserDataset parse(
            byte[] bytes,
            Set<String> platformIds,
            UserDatasetProperties limits
    ) {
        if (bytes == null || bytes.length == 0) {
            throw invalid("CSV 文件不能为空");
        }
        if (bytes.length > limits.maxFileSizeBytes()) {
            throw invalid("CSV 文件不能超过 " + limits.maxFileSizeBytes() + " 字节");
        }
        String text = decodeUtf8(bytes);
        if (!text.isEmpty() && text.charAt(0) == '\ufeff') {
            text = text.substring(1);
        }

        CSVFormat format = CSVFormat.RFC4180.builder()
                .setHeader()
                .setSkipHeaderRecord(true)
                .setIgnoreEmptyLines(true)
                .setTrim(false)
                .get();
        try (CSVParser parser = CSVParser.parse(text, format)) {
            CsvDialect dialect = CsvDialect.fromHeaders(parser.getHeaderNames());
            if (dialect == null) {
                throw invalid("CSV 表头不正确，请直接使用系统下载的模板。中文模板表头必须严格按此顺序："
                        + String.join(",", HEADERS));
            }
            return parseRows(parser, platformIds, limits, dialect);
        } catch (UserDatasetException exception) {
            throw exception;
        } catch (IOException | IllegalArgumentException exception) {
            throw invalid("CSV 格式错误，无法解析；请检查逗号、双引号和换行是否符合模板");
        }
    }

    private ParsedUserDataset parseRows(
            CSVParser parser,
            Set<String> platformIds,
            UserDatasetProperties limits,
            CsvDialect dialect
    ) {
        Map<String, UserDatasetBook> books = new LinkedHashMap<>();
        Map<String, PlatformOffer> offers = new LinkedHashMap<>();
        int rowCount = 0;
        for (CSVRecord record : parser) {
            rowCount++;
            if (rowCount > limits.maxRowCount()) {
                throw invalid(localized(dialect,
                        "CSV 数据行不能超过 " + limits.maxRowCount() + " 行",
                        "CSV must not contain more than " + limits.maxRowCount() + " data rows"));
            }
            if (!record.isConsistent()) {
                throw invalidAt(record, dialect, localized(dialect,
                        "必须正好包含 " + dialect.headers().size() + " 列",
                        "row does not contain exactly " + dialect.headers().size() + " columns"));
            }

            String schemaVersion = value(record, dialect.versionColumn(), dialect);
            if (!dialect.version().equals(schemaVersion)) {
                throw invalidAt(record, dialect, localized(dialect,
                        "数据格式版本必须填写“" + dialect.version() + "”",
                        "schema_version must be " + dialect.version()));
            }
            String isbn = value(record, dialect.isbnColumn(), dialect);
            if (!Isbn13Validator.isValid(isbn)) {
                throw invalidAt(record, dialect, localized(dialect,
                        "ISBN 必须是有效的 13 位 ISBN",
                        "isbn must be a valid ISBN-13"));
            }
            String title = value(record, dialect.titleColumn(), dialect);
            if (title.isBlank() || title.length() > 200) {
                throw invalidAt(record, dialect, localized(dialect,
                        "书名长度必须在 1 到 200 个字符之间",
                        "title length must be between 1 and 200"));
            }
            if (isSpreadsheetFormula(title)) {
                throw invalidAt(record, dialect, localized(dialect,
                        "书名不能以 =、+、- 或 @ 开头",
                        "title must not start with =, +, -, or @"));
            }
            int quantity = parseInteger(record, dialect.quantityColumn(), dialect);
            if (quantity < 1 || quantity > InputLimits.MAX_QUANTITY_PER_INVENTORY_ENTRY) {
                throw invalidAt(record, dialect, localized(dialect,
                        "数量必须在 1 到 " + InputLimits.MAX_QUANTITY_PER_INVENTORY_ENTRY + " 之间",
                        "quantity must be between 1 and " + InputLimits.MAX_QUANTITY_PER_INVENTORY_ENTRY));
            }
            String platformId = parsePlatform(record, dialect, platformIds);
            OfferStatus status = parseStatus(record, dialect);
            RepeatPolicy repeatPolicy = parseRepeatPolicy(record, dialect);
            String priceText = value(record, dialect.priceColumn(), dialect);
            long priceCents = parsePrice(record, dialect, status, priceText);
            if (status != OfferStatus.ACCEPTED && repeatPolicy != RepeatPolicy.INHERIT_PLATFORM) {
                throw invalidAt(record, dialect, localized(dialect,
                        "回收状态为“不回收”或“未知”时，重复书限制必须留空",
                        "REJECTED or UNKNOWN rows must use INHERIT_PLATFORM"));
            }

            UserDatasetBook incomingBook = new UserDatasetBook(isbn, title, quantity);
            UserDatasetBook existingBook = books.putIfAbsent(isbn, incomingBook);
            if (existingBook != null && (!existingBook.title().equals(title)
                    || existingBook.quantity() != quantity)) {
                throw invalidAt(record, dialect, localized(dialect,
                        "同一 ISBN 在每个平台行中的书名和数量必须一致",
                        "title and quantity must be identical on every row for one ISBN"));
            }
            if (books.size() > limits.maxIsbnCount()) {
                throw invalid(localized(dialect,
                        "CSV 中的 ISBN 不能超过 " + limits.maxIsbnCount() + " 个",
                        "CSV must not contain more than " + limits.maxIsbnCount() + " ISBN values"));
            }
            String key = isbn + '\u0000' + platformId;
            PlatformOffer offer = new PlatformOffer(isbn, platformId, status, priceCents, repeatPolicy);
            if (offers.putIfAbsent(key, offer) != null) {
                throw invalidAt(record, dialect, localized(dialect,
                        "同一本书不能重复填写同一平台：" + isbn + "/" + displayPlatform(platformId),
                        "duplicate ISBN/platform pair: " + isbn + "/" + platformId));
            }
        }
        if (rowCount == 0) {
            throw invalid(localized(dialect, "CSV 至少需要一行报价数据", "CSV must contain at least one data row"));
        }
        int totalQuantity = books.values().stream().mapToInt(UserDatasetBook::quantity).sum();
        if (totalQuantity > InputLimits.MAX_TOTAL_INVENTORY_QUANTITY) {
            throw invalid(localized(dialect,
                    "所有不同 ISBN 的数量总和不能超过 " + InputLimits.MAX_TOTAL_INVENTORY_QUANTITY,
                    "sum of distinct ISBN quantities must not exceed "
                            + InputLimits.MAX_TOTAL_INVENTORY_QUANTITY));
        }
        validateCompleteMatrix(books.keySet(), platformIds, offers.values(), dialect);
        return new ParsedUserDataset(
                dialect.version(),
                new ArrayList<>(books.values()),
                new ArrayList<>(offers.values()),
                rowCount
        );
    }

    private static String parsePlatform(CSVRecord record, CsvDialect dialect, Set<String> platformIds) {
        String supplied = value(record, dialect.platformColumn(), dialect);
        String platformId;
        if (dialect.userFacing()) {
            platformId = USER_PLATFORM_IDS.get(supplied);
            if (platformId == null && supplied.toLowerCase(Locale.ROOT).startsWith("platform-")) {
                platformId = supplied.toLowerCase(Locale.ROOT);
            }
            if (platformId == null) {
                throw invalidAt(record, dialect,
                        "平台只支持平台A、平台B、平台C、平台D、平台E或模板中的稳定 platform-* 代号");
            }
        } else {
            platformId = supplied;
        }
        if (!platformIds.contains(platformId)) {
            throw invalidAt(record, dialect, localized(dialect,
                    "平台不属于当前选择的基础数据集：" + supplied,
                    "platform_id is not part of the selected base dataset: " + platformId));
        }
        return platformId;
    }

    private static OfferStatus parseStatus(CSVRecord record, CsvDialect dialect) {
        String supplied = value(record, dialect.statusColumn(), dialect);
        if (dialect.userFacing()) {
            OfferStatus status = USER_STATUSES.get(supplied);
            if (status == null) {
                throw invalidAt(record, dialect, "回收状态只支持：回收、不回收、未知");
            }
            return status;
        }
        return parseLegacyEnum(record, dialect, dialect.statusColumn(), supplied, OfferStatus.class);
    }

    private static RepeatPolicy parseRepeatPolicy(CSVRecord record, CsvDialect dialect) {
        String supplied = value(record, dialect.repeatPolicyColumn(), dialect);
        if (dialect.userFacing()) {
            RepeatPolicy policy = USER_REPEAT_POLICIES.get(supplied);
            if (policy == null) {
                throw invalidAt(record, dialect,
                        "重复书限制只支持：1（可按数量回收）、0（每个订单最多一本）或留空（沿用平台默认）");
            }
            return policy;
        }
        return parseLegacyEnum(record, dialect, dialect.repeatPolicyColumn(), supplied, RepeatPolicy.class);
    }

    private static <E extends Enum<E>> E parseLegacyEnum(
            CSVRecord record,
            CsvDialect dialect,
            String column,
            String supplied,
            Class<E> type
    ) {
        String normalized = supplied.toUpperCase(Locale.ROOT);
        try {
            return Enum.valueOf(type, normalized);
        } catch (IllegalArgumentException exception) {
            throw invalidAt(record, dialect, column + " has unsupported value: " + normalized);
        }
    }

    private static void validateCompleteMatrix(
            Set<String> isbns,
            Set<String> platformIds,
            java.util.Collection<PlatformOffer> offers,
            CsvDialect dialect
    ) {
        Map<String, Set<String>> actual = new HashMap<>();
        for (PlatformOffer offer : offers) {
            actual.computeIfAbsent(offer.isbn(), ignored -> new HashSet<>()).add(offer.platformId());
        }
        for (String isbn : isbns) {
            Set<String> supplied = actual.getOrDefault(isbn, Set.of());
            if (!supplied.equals(platformIds)) {
                Set<String> missing = new HashSet<>(platformIds);
                missing.removeAll(supplied);
                List<String> missingLabels = missing.stream().sorted()
                        .map(id -> dialect.userFacing() ? displayPlatform(id) : id)
                        .toList();
                throw invalid(localized(dialect,
                        "ISBN " + isbn + " 必须为每个平台各填写一行；缺少：" + missingLabels,
                        "ISBN " + isbn + " must contain exactly one row for every platform; missing: "
                                + missingLabels));
            }
        }
    }

    private static String decodeUtf8(byte[] bytes) {
        try {
            return StandardCharsets.UTF_8.newDecoder()
                    .onMalformedInput(CodingErrorAction.REPORT)
                    .onUnmappableCharacter(CodingErrorAction.REPORT)
                    .decode(ByteBuffer.wrap(bytes))
                    .toString();
        } catch (CharacterCodingException exception) {
            throw invalid("CSV 必须使用 UTF-8 编码（允许带 UTF-8 BOM）");
        }
    }

    private static long parsePrice(
            CSVRecord record,
            CsvDialect dialect,
            OfferStatus status,
            String text
    ) {
        if (status != OfferStatus.ACCEPTED) {
            if (!text.isBlank()) {
                throw invalidAt(record, dialect, localized(dialect,
                        "只有回收状态为“回收”时才能填写单本价格",
                        "unit_price_yuan must be blank unless status is ACCEPTED"));
            }
            return 0;
        }
        if (text.isBlank()) {
            throw invalidAt(record, dialect, localized(dialect,
                    "回收状态为“回收”时必须填写单本价格",
                    "unit_price_yuan is required when status is ACCEPTED"));
        }
        try {
            BigDecimal yuan = new BigDecimal(text).setScale(2, RoundingMode.UNNECESSARY);
            long cents = yuan.movePointRight(2).longValueExact();
            if (cents <= 0 || cents > MAX_PRICE_CENTS) {
                throw invalidAt(record, dialect, localized(dialect,
                        "回收价格必须在 0.01 元到 10000.00 元之间",
                        "accepted price must be between 0.01 and 10000.00 yuan"));
            }
            return cents;
        } catch (ArithmeticException | NumberFormatException exception) {
            throw invalidAt(record, dialect, localized(dialect,
                    "单本价格必须是最多保留两位小数的数字",
                    "unit_price_yuan must be a decimal with at most two fraction digits"));
        }
    }

    private static int parseInteger(CSVRecord record, String column, CsvDialect dialect) {
        try {
            return Integer.parseInt(value(record, column, dialect));
        } catch (NumberFormatException exception) {
            throw invalidAt(record, dialect, localized(dialect,
                    column + "必须填写整数",
                    column + " must be an integer"));
        }
    }

    private static String value(CSVRecord record, String column, CsvDialect dialect) {
        String raw = record.get(column);
        if (raw.codePoints().anyMatch(Character::isISOControl)) {
            throw invalidAt(record, dialect, localized(dialect,
                    column + "不能包含控制字符",
                    column + " must not contain control characters"));
        }
        return raw.strip();
    }

    private static boolean isSpreadsheetFormula(String value) {
        if (value.isEmpty()) {
            return false;
        }
        return switch (value.charAt(0)) {
            case '=', '+', '-', '@' -> true;
            default -> false;
        };
    }

    private static String displayPlatform(String id) {
        return USER_PLATFORM_IDS.entrySet().stream()
                .filter(entry -> entry.getValue().equals(id))
                .map(Map.Entry::getKey)
                .findFirst()
                .orElse(id);
    }

    private static String localized(CsvDialect dialect, String chinese, String english) {
        return dialect.userFacing() ? chinese : english;
    }

    private static UserDatasetException invalidAt(CSVRecord record, CsvDialect dialect, String message) {
        return invalid(dialect.userFacing()
                ? "第 " + record.getRecordNumber() + " 行：" + message
                : "row " + record.getRecordNumber() + ": " + message);
    }

    private static UserDatasetException invalid(String message) {
        return new UserDatasetException(UserDatasetErrorCode.INVALID_CSV, List.of(message));
    }

    private enum CsvDialect {
        USER_FACING(
                SCHEMA_VERSION,
                HEADERS,
                "数据格式版本", "ISBN", "书名", "数量", "平台", "回收状态", "单本价格（元）", "重复书限制",
                true
        ),
        LEGACY(
                LEGACY_SCHEMA_VERSION,
                LEGACY_HEADERS,
                "schema_version", "isbn", "title", "quantity", "platform_id", "status",
                "unit_price_yuan", "repeat_policy",
                false
        );

        private final String version;
        private final List<String> headers;
        private final String versionColumn;
        private final String isbnColumn;
        private final String titleColumn;
        private final String quantityColumn;
        private final String platformColumn;
        private final String statusColumn;
        private final String priceColumn;
        private final String repeatPolicyColumn;
        private final boolean userFacing;

        CsvDialect(
                String version,
                List<String> headers,
                String versionColumn,
                String isbnColumn,
                String titleColumn,
                String quantityColumn,
                String platformColumn,
                String statusColumn,
                String priceColumn,
                String repeatPolicyColumn,
                boolean userFacing
        ) {
            this.version = version;
            this.headers = headers;
            this.versionColumn = versionColumn;
            this.isbnColumn = isbnColumn;
            this.titleColumn = titleColumn;
            this.quantityColumn = quantityColumn;
            this.platformColumn = platformColumn;
            this.statusColumn = statusColumn;
            this.priceColumn = priceColumn;
            this.repeatPolicyColumn = repeatPolicyColumn;
            this.userFacing = userFacing;
        }

        static CsvDialect fromHeaders(List<String> headers) {
            for (CsvDialect dialect : values()) {
                if (dialect.headers.equals(headers)) {
                    return dialect;
                }
            }
            return null;
        }

        String version() {
            return version;
        }

        List<String> headers() {
            return headers;
        }

        String versionColumn() {
            return versionColumn;
        }

        String isbnColumn() {
            return isbnColumn;
        }

        String titleColumn() {
            return titleColumn;
        }

        String quantityColumn() {
            return quantityColumn;
        }

        String platformColumn() {
            return platformColumn;
        }

        String statusColumn() {
            return statusColumn;
        }

        String priceColumn() {
            return priceColumn;
        }

        String repeatPolicyColumn() {
            return repeatPolicyColumn;
        }

        boolean userFacing() {
            return userFacing;
        }
    }
}
